### ISSUE TITLE
Dependencies conflict

### ISSUE THREAD

**Issue by ecooper7** [JasonSWFu/VQscore#5]
Hello, thank you very much for your nice paper and for releasing your code!

I am just now trying to set up the dependencies to be able to use VQScore.  According to the README, I should use Python 3.8, and according to the requirements.txt file, I should use scipy==1.12.0.  However, when I run `pip install scipy==1.12.0` I get an error that no matching distribution is found, and only earlier versions of scipy are available for Python 3.8.  This is confirmed by the version compatibility table here:  https://docs.scipy.org/doc/scipy-1.12.0/dev/toolchain.html which shows that scipy 1.12.0 requires Python 3.9 or higher.  What is your recommendation for being able to set up VQScore the most easily?  Can I use a newer Python, or an older scipy?

**Comment by JasonSWFu** [comment]
Hello Erica,

Thanks for your interest.
I think using older scipy might not cause problems.

SW

**Comment by ecooper7** [comment]
Thanks so much!  Using scipy==1.10 I was able to get all the dependencies installed and successfully run both of the inference examples.
